---
title: "`R` para Ciência de Dados: Introdução à Programação em `R`"
format: html
author: Gilberto Sassi
date: 2024/10/18
categories:
  - Ciência de Dados
  - R
  - Programação
  - Base de dados
  - Laço de repetição
  - Controle de fluxo
---

## Slides

[Slides](slides_programacao_r.html){target="_blank"}

## `codeshare.io`

[codeshare.io/VNdlJ4](https://codeshare.io/VNdlJ4){target="_blank"}

## Arquivos

[projeto_programacao_r.zip](projeto_programacao_r.zip)

## `R` e `Rstudio`

Neste curso, a IDE vamos utilizar é o [`RStudio`](https://posit.co/downloads/){target="_blank"}. Outras opções populares em ciência de dados são o [`VScode`](https://code.visualstudio.com/Download){target="_blank"} da Microsoft e [`JupyterLab`](https://jupyter.org/install){target="_blank"}, caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas [Google Colaboratory](https://colab.research.google.com/){target="_blank"} e/ou [Posit Cloud](https://posit.cloud){target="_blank"}. Recomendamos o uso da plataforma [Posit Cloud](https://posit.cloud){target="_blank"} pelo mesmo estilo e aspecto visual do aplicativo [`RStudio`](https://posit.co/downloads/){target="_blank"}.

### Instalação -`R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do R.

### Instalação - `RStudio`

Depois de ter instalado o R, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

---
