---
title: "Intervalos de Confiança e Testes de Hipóteses"
---

# Resumo

O objetivo deste curso é compartilhar o conhecimento de análise estatística de dados, principalmente métodos de inferência estatística, usando a linguagem `R` numa interação dialógica da comunidade acadêmica com a sociedade por meio da troca de conhecimentos. A ação cumprirá o papel de aproximar a academia da comunidade, popularizando a ciência Estatística e trazendo para dentro da universidade a experiência e a grande demanda que profissionais têm de usar Estatística e Ciência de Dados. A ação procurará integrar discentes em sua equipe organizadora. A atividade se propõe a introduzir os conceitos de intervalos de confiança e testes de hipóteses, métodos estatísticos amplamente usados, utilizando o pacote `statBasics`.

O curso terá 8 horas com 2 encontros presenciais com duração de quatro horas nos laboratórios de ensino de informática do IME-UFBA, será gratuito com certificado emitido pela UFBA e terá 15 vagas.

# Área

De acordo com o disposto na Política Nacional de Extensão, este Projeto de Extensão está vinculado às áreas temáticas descritas a seguir.

- **Linha Programática:** Educação profissional;
- **Área(s) de Conhecimento(s):** Ciências Exatas e da Terra;
- **Área(s) Temáticas(s):** Tecnologia.

# Coordenação

- Professor Doutor Gilberto Pereira Sassi, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.
- Professora Doutora Carolina Costa Mota Paraíba, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.

Justificativa da necessidade do segundo coordenador: a Profa. Carolina é responsável por coordenar a ampla divulgação do curso entre os profissionais que fazem uso de análise estatística de dados, o processo de inscrição, a construção do site do curso, a elaboração de material didático e manutenção das bases de dados usadas neste curso.

# Universidade universitária

Instituto de Matemática e Estatística da Universidade Federal da Bahia.

# Público alvo

Profissionais que usam análises estatísticas de dados.

# Número esperado de participantes

20

# Local de realização

Laboratório de ensino de informática do IME-UFBA.

# Metodologia

Metodologia do curso será de aulas expositivas e práticas em laboratório de informática usando a linguagem R.

# Conteúdo programático

1. Breve revisão de `R`, `RStudio` e `tidyverse`
2. Breve introdução à variável aleatória
3. Intervalo de confiança para uma população usando o pacote `statBasics`
4. Teste de hipóteses para uma população usando o pacote `statBasics`

---
