---
title: "Produção de Texto usando rmarkdown e quarto"
---

# Resumo

O objetivo deste curso é compartilhar o conhecimento da linguagem `R` numa interação dialógica da comunidade acadêmica com a sociedade por meio da troca de conhecimentos. A ação cumprirá o papel de aproximar a academia da comunidade, popularizando o uso de software livre e da linguagem `R` e trazendo para dentro da universidade a experiência e a grande demanda que profissionais têm de usar software livre e, em especial, a linguagem `R`. A ação procurará integrar discentes em sua equipe organizadora. O curso se propõe a apresentar dois pacotes da linguagem `R`: `rmarkdown` e `quarto`, que são especialmente úteis para redação de textos no formato `.pdf` (incluindo apresentações em `beamer`), `.html` (incluindo apresentações apresentações em `ioslide`), e `.docx`. O curso terá 8 horas com 2 encontros presenciais com duração de quatro horas nos laboratórios de ensino de informática do IME-UFBA, será gratuito com certificado emitido pela UFBA e terá 20 vagas.

# Área

De acordo com o disposto na Política Nacional de Extensão, este Projeto de Extensão está vinculado às áreas temáticas descritas a seguir.

- **Linha Programática:** Educação profissional;
- **Área(s) de Conhecimento(s):** Ciências Exatas e da Terra;
- **Área(s) Temáticas(s):** Tecnologia.

# Coordenação

- Professor Doutor Gilberto Pereira Sassi, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.
- Professora Doutora Carolina Costa Mota Paraíba, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.

Justificativa da necessidade do segundo coordenador: a Profa. Carolina é responsável por coordenar a ampla divulgação do curso entre os profissionais que fazem uso de análise estatística de dados, o processo de inscrição, a construção do site do curso, a elaboração de material didático e manutenção das bases de dados usadas neste curso.

# Universidade universitária

Instituto de Matemática e Estatística da Universidade Federal da Bahia.

# Público alvo

Profissionais que usam análises estatísticas de dados.

# Número esperado de participantes

20

# Local de realização

Laboratório de ensino de informática do IME-UFBA.

# Metodologia

metodologia do curso será de aulas expositivas e práticas em laboratório de informática usando a linguagem R.

# Conteúdo programático

1. Breve apresentação da linguagem `R` e `RStudio`;
2. Preparação de documentos `pdf` usando `rmardown` (através da linguagem `latex`): `rticle` e `beamer`;
3. Preparação de documento `html` usando `rmardown`: `ioslide` e `prettydoc`, e publicação usando `github pages` e `netlify`;
4. Preparação de documentos `docx` usando `rmarkdown`;
5. Apresentação de `quarto`: `rmarkdown` para `python,` `R` e `julia`.

---