<div style="text-align:justify">

# Edital público em Extensão Universitária

Estão abertas inscrições para seleção de **01 vaga para bolsista e 02 vagas para voluntário** para os Semestres Letivos 2023.2  e 2024.1 no Projeto de Extensão **`R` para Ciência de Dados**, sob número de cadastro 19588 na plataforma SIATEX. 

O objetivo deste projeto de extensão é compartilhar o conhecimento de análise de dados usando a linguagem `R` numa interação dialógica da comunidade acadêmica com a sociedade por meio da troca de conhecimentos. O projeto irá promover um conjunto de ações com o objetivo de popularizar a Estatística e Ciência de Dados e incentivar o uso de tecnologias de código aberto como a linguagem `R`, cujo uso é amplamente disseminado entre os pesquisadores da área de Estatística com crescente popularidade entre profissionais de outras áreas. Os métodos que serão abordados neste projeto constituem um conhecimento essencial para o exercício da cidadania devido ao avanço das tecnologias de informação. As ações planejadas neste projeto trarão para a universidade a experiência e a demanda dos profissionais pelo uso de Estatística e Ciência de Dados. Devido a relevância e atualidade do tema, é importante que a UFBA atue junto com a sociedade em atividades gratuitas fortalecendo a inserção da UFBA dentro da sociedade.


## Vagas ofertadas

- 01 vaga para bolsista de Extensão, no valor de R$700,00 mensal, conforme Edital [PIBIEX 2023-2024](https://sisbiex.ufba.br/sisbiex//fileAnexoArquivo?n=Sisbiex_E_34.pdf){target="_blank"}.
- 02 vagas para voluntárias/os, com até R$1.000,00 de auxílio financeiro para ajuda de custo, conforme Edital [PAEx 2023](https://sapex.ufba.br/sapex//fileAnexoArquivo?n=Sapex_E_164.pdf){target="_blank"}.



## Requisitos para candidatura

As vagas estão aberta para qualquer estudante de graduação da UFBA que atenda aos seguintes requisitos:

- a/o candidata/o deve ser estudante regularmente matriculada/o em qualquer curso de graduação oferecido pela UFBA.
- não pode estar inadimplente com a PROEXT.
- no caso de bolsista, não pode acumular bolsa com outro Programa Institucional.
- ter disponibilidade de trabalhar vinte horas semanais nas atividades deste projeto.
- ter coeficiente de rendimento maior ou igual a 6,0.
- desejável conhecimento de linguagem `R` e/ou Métodos Estatísticos.


## Responsabilidades da/o bolsista

- participar de reuniões semanais com a equipe executora em dia e horário a definir.
- participar das reuniões de orientação e avaliação com a PROEXT.
- participar das atividades promovidas por este projeto de extensão.
- auxiliar na manutenção do website do projeto de extensão.
- enviar relatório de atividades no sistema SISBIEX, usando formulário próprio, em até 30 (trinta) dias após a conclusão do projeto,
- apresentar os resultados dos planos de trabalhos na próxima edição do Congresso UFBA.


## Responsabilidades da/o voluntária/o

- participar de reuniões semanais com a equipe executora em dia e horário a definir.
- participar das reuniões de orientação e avaliação com a PROEXT.
- participar das atividades promovidas por este projeto de extensão.
- enviar relatório de atividades no sistema SISBIEX, usando formulário próprio, em até 30 (trinta) dias após a conclusão do projeto,
- apresentar os resultados dos planos de trabalhos na próxima edição do Congresso UFBA.


## Critérios que serão usados para seleção

Em ordem de importância:

1. entrevista em que se avaliará a disponibilidade e adequação da/o candidata/o para a vaga (nota de 0 a 10),
2. nível de conhecimento de Métodos Estatísticos (nota de 0 a 10).
3. nível de conhecimento da linguagem `R` (nota de 0 a 10).

## Inscrição

Para se candidatar as vagas, você precisa preencher o seguinte formulário de inscrição: [formulário de inscrição](https://forms.gle/mg3aPbCxxC29bzmY6){target="_blank"}.

O período de inscrição é de 17/07/2023 a 20/07/2023. 

Eventuais dúvidas podem ser encaminhadas a [gilberto.sassi`@`ufba.br](mailto:gilberto.sassi@ufba.br).

## Resultados

A/o primeiro colocado ficará com a bolsa PIBIEX, e a/os segunda/a e terceira/o colocada/o serão voluntárias/os vinculados ao PAEX, conforme descrito acima.

Os coordenadores pedem, gentilmente, que respondam os e-mails confirmando interesse até amanhã, dia 26/07/2023, às 10h00min sem falta.

```{r}
#| echo: false
#| message: false
library(readxl)
library(gt)
library(tidyverse)

dados <- read_xlsx("../../assets/selecao.xlsx")

dados <- dados |>
    select(nome, disponibilidade, estatistica, r, nota) |>
    arrange(desc(nota), nome)

gt(dados) |>
    tab_header(title = "Classificação das/os inscritas/os.") |>
    fmt_number(
        c(disponibilidade, estatistica, r, nota),
        decimals = 2,
        sep_mark = ".",
        dec_mark = ","
    ) |>
    cols_label(
        nome = md("**Nome**"),
        disponibilidade = md("**Disponibilidade**"),
        estatistica = md("**Conhecimento em estatística**"),
        r = md("**Conhecimento da linguagem `R`**"),
        nota = md("**Nota final**")
    )   
```

</div>

---
