---
title: "`R` para Ciência de Dados"
---

<div style="text-align:justify">

Em 29 de abril de 2024, as/os docentes da UFBA se somaram aos docentes em todo o Brasil na luta pela recomposição de seus salários, contra os cortes no orçamento e por mais investimentos na IFES! O Comando Local de Greve das/os Docentes da UFBA, através da sua Comissão de Ética, definiu em comunicado divulgado em 30 de abril de 2024 quais atividades são essenciais e quais estão suspensas.

O projeto de extensão **`R` para Ciência de Dados**, se enquadra como uma atividade que não está suspensa porque já foram empenhados recursos financeiros e atende a comunidade externa. Portanto, este projeto de extensão será realizado conforme planejado. Reconhecemos a legalidade e legitimidade da greve das/os docentes da UFBA. É preciso lutar pelas nossas Universidades Públicas que oferecem ensino gratuito e de qualidade!

Para saber sobre a greve docente nacional: visite [`@andessindicato`](https://www.instagram.com/andessindicato/){target="_blank"} no Instagram.

Para saber sobre a greve dos TAES: visite [`@fasubrasindical`](https://www.instagram.com/fasubrasindical/){target="_blank"} no Instagram.

Para saber sobre a greve nos Institutos Federais: visite [`@sinasefe`](https://www.instagram.com/sinasefe/){target="_blank"} no Instagram.

Para saber sobre a greve docente na UFBA: visite [`@coletivodemocraciaeluta`](https://www.instagram.com/coletivodemocraciaeluta/){target="_blank"} no Instagram.

Para saber sobre a greve das/os estudantes de pós-graduação da UFBA: visite [`@apgufba`](https://www.instagram.com/apgufba/){target="_blank"} no Instagram.

Comunicado da Comissão de Ética do Comando Local de Greve das/os Docentes da UFBA: [Comunidade 01 da Comissão de Ética do Comando Local de Greve Docente da UFBA](https://apub.org.br/comunicado-da-comissao-de-etica-do-comando-de-greve-da-ufba/){target="_blank"}.

Governo comprometido com a Educação investe na Educação!

Governo comprometido com a Educação não corta orçamento da Educação!

Governo comprometido com a Educação valoriza as/os trabalhadoras/es da Educação!

<!-- `R`  para Ciência de dados é uma ação de extensão na modalidade _projeto_ com apoio financeiro da Pró-reitoria de Extensão da Univesidade Federal da Bahia (UFBA) e tem como o objetivo  compartilhar o conhecimento de análise de dados usando a linguagem `R` numa interação dialógica da comunidade acadêmica com a sociedade por meio da troca de conhecimentos. 

O projeto irá promover um conjunto de ações com o objetivo de popularizar a Estatística e Ciência de Dados e incentivar o uso de tecnologias de código aberto como a linguagem `R`, cujo uso é amplamente disseminado entre os pesquisadores da área de Estatística com crescente popularidade entre profissionais de outras áreas.

Os cursos e eventos promovidos neste projeto serão presenciais em Salvador no Instituto de Matemática e Estatística da UFBA, gratuitas, abertas a toda comunidade e com certificado emitado pela UFBA. 

<div style="text-align: center;">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1731.7044864127633!2d-38.50767380792866!3d-13.00092642626354!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x716049fbfc20d8b%3A0x5a3ed51534624abc!2sInstituto%20de%20Matem%C3%A1tica%20e%20Estat%C3%ADstica%20da%20UFBA!5e0!3m2!1spt-BR!2sbr!4v1710436162475!5m2!1spt-BR!2sbr" width="75%" height="300em" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div> -->

**Defenda a Universidade pública, gratuita, de qualidade e diversa.**<br>
**Serviço público salva vidas. Defenda o serviço público.**

> De cada qual, segundo sua capacidade; a cada qual, segundo suas necessidades.

</div>


---
