---
title: "`R` para Ciência de Dados: Regressão Linear Simples e Múltipla"
author: "Carolina Costa Mota Paraíba"
date: "2024/04/19"
categories:
  - Ciência de Dados
  - Estatística descritiva
  - Regressão Linear Simples
  - Regressão Linear Múltipla
  - Regressão Linear
  - Apredizagem Supervisionada
---

## Slides

[aula_rls.pdf](aula_rls.pdf){target="_blank"}<br>
[aula_rlm.pdf](aula_rlm.pdf){target="_blank"}

## Dados

[dados_rls.xlsx](dados_rls.xlsx)<br>
[dados_rlm.xlsx](dados_rlm.xlsx)<br>
[mtcarros.xlsx](mtcarros.xlsx)

## Código da sala de aula

O código da sala de aula está em [codeshare.io/9bjkmg](https://codeshare.io/9bjkmg){target="_blank"}.

## `R` e `Rstudio`

Neste curso, a IDE vamos utilizar é o [`RStudio`](https://posit.co/downloads/){target="_blank"}. Outras opções populares em ciência de dados são o [`VScode`](https://code.visualstudio.com/Download){target="_blank"} da Microsoft e [`JupyterLab`](https://jupyter.org/install){target="_blank"}, caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas [Google Colaboratory](https://colab.research.google.com/){target="_blank"} e/ou [Posit Cloud](https://posit.cloud){target="_blank"}. Recomendamos o uso da plataforma [Posit Cloud](https://posit.cloud){target="_blank"} pelo mesmo estilo e aspecto visual do aplicativo [`RStudio`](https://posit.co/downloads/){target="_blank"}.

### Instalação -`R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do R.

### Instalação - `RStudio`

Depois de ter instalado o R, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

---
