---
title: "`R` para Ciência de Dados: Exploração e Visualização de Dados"
author: "Gilberto Pereira Sassi"
date: "2024/03/16"
categories:
  - Ciência de Dados
  - Estatística descritiva
  - Exploração e visualização de dados
  - Medidas de resumo
  - Gráfico de barras
  - Histograma
---

## Slides

[slides.pdf](slides.pdf){target="_blank"}

## Dados

[arquivos.zip](arquivos.zip){target="_blank"}

## Dados - ENEM

Dicionário de dados: [dicionario.xlsx](cidades-enem-2022/dicionario.xlsx).

```{r}
#| echo: false
#| message: false

if (!require(pacman)) {
  install.packages("pacman")
  library(pacman)
}


p_load(
  glue,
  readxl,
  writexl,
  htmltools,
  gt,
  tidyverse
)
# setwd("paginas/material/2024/marco")
df_inscritos <- read_excel("lista-inscritos.xlsx")

nomes <- df_inscritos$nome_completo
nomes <- c(
  nomes, 
  rep("--", 5)
)

set.seed(11235)
id <- sample(
  seq_len(30)
)

# setwd("paginas/material/2024/marco")
arq_csv <- list.files("cidades-enem-2022/csv")
arq_csv <- arq_csv[arq_csv != "salvador.csv"]
arq_xlsx <- list.files("cidades-enem-2022/xlsx")
arq_xlsx <- arq_xlsx[arq_xlsx != "salvador.xlsx"]

df <- tibble(
  id = id,
  nome = nomes,
  csv = arq_csv |>
    map(\(arq) {
      gt::md(str_interp("[${arq}](cidades-enem-2022/csv/${arq})"))
    }),
  xlsx = arq_xlsx |>
    map(\(arq) {
      gt::md(str_interp("[${arq}](cidades-enem-2022/xlsx/${arq})"))
    })
) |>
  arrange(id)


knitr::kable(df, caption = "Enem por cidade nos formatos .csv e .xlsx com id dos participantes.")
```


## `R` e `Rstudio`

Neste curso, a IDE vamos utilizar é o [`RStudio`](https://posit.co/downloads/){target="_blank"}. Outras opções populares em ciência de dados são o [`VScode`](https://code.visualstudio.com/Download){target="_blank"} da Microsoft e [`JupyterLab`](https://jupyter.org/install){target="_blank"}, caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas [Google Colaboratory](https://colab.research.google.com/){target="_blank"} e/ou [Posit Cloud](https://posit.cloud){target="_blank"}. Recomendamos o uso da plataforma [Posit Cloud](https://posit.cloud){target="_blank"} pelo mesmo estilo e aspecto visual do aplicativo [`RStudio`](https://posit.co/downloads/){target="_blank"}.

### Instalação -`R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do R.

### Instalação - `RStudio`

Depois de ter instalado o R, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

---