---
title: "`R` para Ciência de Dados: Exploração e Visualização de Dados"
author: "Carolina Costa Mota Paraíba"
date: "2023/10/20"
categories:
  - Ciência de Dados
  - Estatística descritiva
  - Exploração e visualização de dados
  - Medidas de resumo
  - Gráfico de barras
  - Histograma
---

<div style="text-align:justify">

# Avisos

Infelizmente, a segunda aula que seria dia 03/11/2023 está cancelada, pois o campus Ondina/Federação da UFBA estará fechado por causa do feriado prolongado de Finados. **Então, a segunda aula será remarcada para o dia 10/11/2023.**

**Lembrando que dia 27/10/2023 não teremos aula.**

---

## Slides

[slides](aula.pdf){target="_blank"}

## Conjunto de Dados

[economia_us.xlsx](economia_us.xlsx)<br>
[estudantes.xlsx](estudantes.xlsx)<br>
[renda_vida.xlsx](renda_vida.xlsx)

## Código das aulas

[Código apresentado durante as aulas.](https://gist.github.com/cienciadedados-ime/f7bb4abbcbe096d4030efa861b67baa3){target="_blank"}

## Instalação do `R` e do `RStudio`

Neste curso, a IDE vamos utilizar é o `RStudio`. Outras opções populares em ciência de dados são o `VScode` da Microsoft e `JupyterLab,` caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas *Google Colaboratory* [colab.to/r](https://colab.to/r) e/ou *RStudio Cloud* [posit.cloud](https://posit.cloud/). Recomendamos o uso da plataforma *RStudio Cloud* pelo mesmo estilo e aspecto visual do aplicativo `RStudio`.

## Para instalar o `R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do `R`.

## Para instalar o `RStudio`

Depois de ter instalado o `R`, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

</div>

---
