---
title: "`R` para Ciência de Dados: Intervalos de Confiança e Teste de Hipóteses"
author: "Gilberto Sassi"
date: "2024/06/07"
categories:
  - Ciência de Dados
  - Inferência Estatística
  - Estatística
  - Intervalo de Confiança
  - Teste de Hipóteses
---

## Slides

[slides](slides.pdf){target="_blank"}

## Arquivos (incluindo dados)

[arquivos](arquivos.zip)

## Dados 

Durante as duas aulas deste curso, você vai analisar as informações (dados) de candidatas/os do Exame Nacional do Ensino Médio (ENEM) na edição de 2023. Cada pessoa deste curso será responsável por analisar uma cidade que está lista na @tbl-cidades.

```{r}
#| echo: false
#| message: false
#| tbl-cap: Informações de candidatas/os do ENEM 2023 por cidade.
#| label: tbl-cidades

if (!require(pacman)) {
  install.packages('pacman')
  library(pacman)
}
p_load(readxl, writexl, readODS)
p_load(ggthemes)
p_load(glue)
p_load(statBasics)
p_load(janitor)
p_load(googlesheets4)
p_load(tidyverse)

set.seed(20240603)

# caminho <- "paginas/material/2024/junho/"
caminho <- ""
participantes <- read_csv(glue("{caminho}lista_presenca.csv"))
nomes <- participantes$nome_completo |> sort()
nomes <- c(
    nomes,
    rep("---", 50 - length(nomes))
)
cidades <- list.files(glue("{caminho}cidades_enem_2023/xlsx"))
cidades <- cidades[cidades != "salvador.xlsx"] |> sample()
filename <- cidades |>
    map_chr(\(x) {
        arq <- paste0(caminho, "cidades_enem_2023/xlsx/", x)
        glue("[`{x}`]({arq})")
    })
df <- tibble(id = paste0("id",1:50), nomes, filename)
knitr::kable(
    df,
    col.names = c("ID", "Nome", "Planilha eletrônica (formato .xlsx)")
)
```

## `codeshare.io`

[codeshare.io/BdOqYx](https://codeshare.io/BdOqYx){target="_blank"}

## `R` e `Rstudio`

Neste curso, a IDE vamos utilizar é o [`RStudio`](https://posit.co/downloads/){target="_blank"}. Outras opções populares em ciência de dados são o [`VScode`](https://code.visualstudio.com/Download){target="_blank"} da Microsoft e [`JupyterLab`](https://jupyter.org/install){target="_blank"}, caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas [Google Colaboratory](https://colab.research.google.com/){target="_blank"} e/ou [Posit Cloud](https://posit.cloud){target="_blank"}. Recomendamos o uso da plataforma [Posit Cloud](https://posit.cloud){target="_blank"} pelo mesmo estilo e aspecto visual do aplicativo [`RStudio`](https://posit.co/downloads/){target="_blank"}.

### Instalação -`R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do R.

### Instalação - `RStudio`

Depois de ter instalado o R, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

---