CASE
  WHEN sg_uf_prova = "AC" THEN "Estado do Acre, Brasil"
  WHEN sg_uf_prova = "AL" THEN "Estado de Alagoas, Brasil"
  WHEN sg_uf_prova = "AP" THEN "Estado do Amapá, Brasil"
  WHEN sg_uf_prova = "AM" THEN "Estado do Amazonas, Brasil"
  WHEN sg_uf_prova = "BA" THEN "Estado da Bahia, Brasil"
  WHEN sg_uf_prova = "CE" THEN "Estado do Ceará, Brasil"
  WHEN sg_uf_prova = "DF" THEN "Distrito Federal, Brasil"
  WHEN sg_uf_prova = "ES" THEN "Estado do Espírito Santo, Brasil"
  WHEN sg_uf_prova = "GO" THEN "Estado de Goiás, Brasil"
  WHEN sg_uf_prova = "MA" THEN "Estado do Maranhão, Brasil"
  WHEN sg_uf_prova = "MT" THEN "Estado de Mato Grosso, Brasil"
  WHEN sg_uf_prova = "MS" THEN "Estado de Mato Grosso do Sul, Brasil"
  WHEN sg_uf_prova = "MG" THEN "Estado de Minas Gerais, Brasil"
  WHEN sg_uf_prova = "PA" THEN "Estado do Pará, Brasil"
  WHEN sg_uf_prova = "PB" THEN "Estado da Paraíba, Brasil"
  WHEN sg_uf_prova = "PR" THEN "Estado do Paraná, Brasil"
  WHEN sg_uf_prova = "PE" THEN "Estado de Pernambuco, Brasil"
  WHEN sg_uf_prova = "PI" THEN "Estado do Piauí, Brasil"
  WHEN sg_uf_prova = "RJ" THEN "Estado do Rio de Janeiro, Brasil"
  WHEN sg_uf_prova = "RN" THEN "Estado do Rio Grande do Norte, Brasil"
  WHEN sg_uf_prova = "RS" THEN "Estado do Rio Grande do Sul, Brasil"
  WHEN sg_uf_prova = "RO" THEN "Estado de Rondônia, Brasil"
  WHEN sg_uf_prova = "RR" THEN "Estado de Roraima, Brasil"
  WHEN sg_uf_prova = "SC" THEN "Estado de Santa Catarina, Brasil"
  WHEN sg_uf_prova = "SP" THEN "Estado de São Paulo, Brasil" 
  WHEN sg_uf_prova = "SE" THEN "Estado de Sergipe, Brasil"
  WHEN sg_uf_prova = "TO" THEN "Estado do Tocantins, Brasil"
  ELSE null
END
