---
title: "Exploração de Visualização de dados"
---

# Resumo

Propomos um curso de extensão universitária no IME/UFBA, com o intuito de promover a interação entre a universidade e a comunidade externa. Este curso, ministrado ao longo de dois dias, totalizando oito horas, enfoca a linguagem Python e as bibliotecas [`pandas`](https://pandas.pydata.org/), [`numpy`](https://numpy.org/), [`seaborn`](https://seaborn.pydata.org/), e  [`matplotlib.pyplot`](https://matplotlib.org) para exploração e visualização de dados. O projeto terá protagonismo discente, integrando estudantes na equipe executora para uma experiência prática. Gratuito e livre, o curso emitirá certificado pela UFBA, incentivando a democratização do conhecimento e fortalecendo laços entre academia e sociedade. Essa iniciativa visa preparar as/os participantes na aplicação e interpretação cientificamente correta da Estatística e Ciência de Dados, contribuindo para o desenvolvimento acadêmico e profissional, alinhando-se à missão universitária de disseminar o saber e promover a inclusão digital. Esta ação de extensão prevê 20 vagas.

# Área

De acordo com o disposto na Política Nacional de Extensão, este Projeto de Extensão está vinculado às áreas temáticas descritas a seguir.

- **Linha Programática:** Educação profissional;
- **Área(s) de Conhecimento(s):** Ciências Exatas e da Terra;
- **Área(s) Temáticas(s):** Tecnologia.

# Coordenação

- Professor Doutor Gilberto Pereira Sassi, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.
- Professora Doutora Carolina Costa Mota Paraíba, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.


# Universidade universitária

Instituto de Matemática e Estatística da Universidade Federal da Bahia.

# Público alvo

Profissionais que usam análises estatísticas de dados.

# Número esperado de participantes

20

# Local de realização

Laboratório de ensino de informática do IME-UFBA.

# Metodologia

metodologia do curso será de aulas expositivas e práticas em laboratório de informática usando a linguagem `python`.

# Conteúdo programático

1. Apresentação da linguagem `python`;
2. Apresentação da IDE [`Jupyter Notebook`](https://jupyter.org/) e [Google Colab](https://colab.research.google.com/);
3. Leitura de arquivos `.xlsx`, e `.csv`;
1. Estruturas básicas de dados: `list`, `tuple`, `dict` and `set`;
1. Matrizes e vetores usando arrays do `NumPy`;
1. Apresentação de `Series` e `DataFrame` da `pandas`;
4. Visualização de dados usando `matplotlib.pyplot` e `seaborn`;
5. Medidas de resumo usando o pacote `pandas`;

---
