---
title: "Análise Estatística de Dados em Estudos de Gênero e Diversidade"
---

# Resumo

A ação é parte do Projeto LGBTQIAPN+ na Ciência e será realizada no Laboratório de Informática do IME-UFBA. O objetivo do curso é preparar profissionais da área de Estudos de Gênero e Diversidade para atuar em temas e ambientes nos quais a análise estatística de dados é importante para auxiliar na compreensão de processos sociais e políticos. Participantes que concluírem o curso terão as habilidades técnicas para analisar, aplicar e apresentar dados, e o conhecimento para extrair informações válidas para resolver problemas do mundo real. O curso irá apresentar a linguagem `R` e serão abordados os seguintes tópicos com aplicações de Estudos de Gênero e Diversidade: importação/exportação de conjunto de dados; tabelas de frequência; gráficos e medidas resumo. Serão apresentados pacotes incluídos no `tidyverse`, como o `dplyr` e `ggplot2`. A ação procurará integrar discentes em sua equipe organizadora.

# Área

De acordo com o disposto na Política Nacional de Extensão, este Projeto de Extensão está vinculado às áreas temáticas descritas a seguir.

- **Linha Programática:** Educação profissional;
- **Área(s) de Conhecimento(s):** Ciências Exatas e da Terra;
- **Área(s) Temáticas(s):** Tecnologia.

# Coordenação

- Professor Doutor Gilberto Pereira Sassi, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.
- Professora Doutora Carolina Costa Mota Paraíba, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.

Justificativa da necessidade do segundo coordenador: a Profa. Carolina é responsável por coordenar a ampla divulgação do curso entre os profissionais que fazem uso de análise estatística de dados, o processo de inscrição, a construção do site do curso, a elaboração de material didático e manutenção das bases de dados usadas neste curso.

# Equipe técnica

- Professora Doutora Carolina Costa Mota Paraíba, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.
- Professor Doutor Gilberto Pereira Sassi, Departamento de Estatística, Instituto de Matemática e Estatística, Universidade Federal da Bahia.

# Universidade universitária

Instituto de Matemática e Estatística da Universidade Federal da Bahia.

# Público alvo

Profissionais que usam análises estatísticas de dados.

# Número esperado de participantes

25

# Local de realização

Laboratório de ensino de informática do IME-UFBA.

# Metodologia

metodologia do curso será de aulas expositivas e práticas em laboratório de informática usando a linguagem `R`.

# Conteúdo programático

1. Apresentação da linguagem `R`;
2. Apresentação da IDE `RStudio`
3. Leitura de arquivos `.xlsx`, `.csv` e `.ods`
4. Visualização de dados usando `ggplot2`
5. Medidas de resumo usando o pacote `dplyr`

---