---
title: "Catálogo de cursos"
---

## Linguagem `R` 

||
|:----|
|[Ciência de Dados para Docentes usando o R](catalogo/r/ciencia-de-dados-para-docentes.html)<br>|
|[Exploração e visualização de dados](catalogo/r/exploracao-visualizacao.html)<br>|
|[Intervalos de Confiança e Testes de Hipóteses](catalogo/r/intervalo-confianca-teste-hipoteses.html)<br>|
|[Introdução à Programação em R](catalogo/r/introducao-a-programacao.html)<br>|
|[Modelos de Análise de Variância (Anova)](catalogo/r/modelo-de-analise-de-variancia.html)<br>|
|[Produção de Texto usando Rmarkdown e Quarto](catalogo/r/producao-de-texto-usando-rmarkdown.html)<br>|
|[Regressão Linear Simples e Múltipla](catalogo/r/regressao-linear-simples-e-multipla.html)<br>|
|[Regressão Logística](catalogo/r/regressao-logistica.html)|

## Linguagem `Python`

||
|:----|
|[Exploração e Visualização de Dados](catalogo/python/exploracao-visualizacao-dados.qmd)|

## Outras linguagens

||
|:---|
|[Dashboards Interativos com Looker Studio](catalogo/outras/looker-studio.qmd)|
---
