---
title: "`R` para Ciência de Dados: Modelos de Análise de Variância (Anova)"
author: "Carolina Costa Mota Paraíba"
date: "2024/07/05"
categories:
  - Ciência de Dados
  - Inferência Estatística
  - Estatística
  - Intervalo de Confiança
  - Teste de Hipóteses
  - Anova
  - Modelo de Análise de Variância
  - Modelos Lineares
---

## Slides

[Slides da aula 1](aula1.pdf){target="_blank"}<br>
[Slides da aula 2](aula2.pdf){target="_blank"}

## Arquivos

[Dados da aula 1](dados_aula1.xlsx)<br>
[Dados da aula 2](dados_aula2.xlsx)

## `codeshare.io`

[codeshare.io/vAXz9l](https://codeshare.io/vAXz9l){target="_blank"}

## `R` e `Rstudio`

Neste curso, a IDE vamos utilizar é o [`RStudio`](https://posit.co/downloads/){target="_blank"}. Outras opções populares em ciência de dados são o [`VScode`](https://code.visualstudio.com/Download){target="_blank"} da Microsoft e [`JupyterLab`](https://jupyter.org/install){target="_blank"}, caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas [Google Colaboratory](https://colab.research.google.com/){target="_blank"} e/ou [Posit Cloud](https://posit.cloud){target="_blank"}. Recomendamos o uso da plataforma [Posit Cloud](https://posit.cloud){target="_blank"} pelo mesmo estilo e aspecto visual do aplicativo [`RStudio`](https://posit.co/downloads/){target="_blank"}.

### Instalação -`R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do R.

### Instalação - `RStudio`

Depois de ter instalado o R, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

---
