---
title: "Dashboards Interativos com Looker Studio"
format: html
author: Gilberto Pereira Sassi
date: 2024/12/16
categories:
  - Ciência de Dados
  - Looker Studio
  - Estatística
  - Gráficos
  - Tabelas
  - Visualização de dados
  - Painel de dados
  - Dashboards
---

## Slides

[Slides](slides.html){target="_blank"}

## `codeshare.io`

**Não altere (apenas copiei) o seguinte código do link abaixo:**

[codeshare.io/MknLxJ](https://codeshare.io/MknLxJ){target="_blank"}

## Arquivos

[`arquivos.zip`](arquivos.zip)

```{r}
#| echo: false
#| message: false
#| tbl-cap: Cada pessoa tem uma cidade, e cada cidade tem uma amostra de 3500 candidatas/os no ENEM na edição 2023.

pacman::p_load(readxl, janitor, glue, tidyverse)

# setwd("paginas/material/2024/dezembro")

arquivos_csv <- list.files("cidades_enem_2023/csv/")
arquivos_csv <- arquivos_csv[arquivos_csv != "salvador.csv"]
arquivos_xlsx <- list.files("cidades_enem_2023/xlsx/")
arquivos_xlsx <- arquivos_xlsx[arquivos_xlsx != "salvador.xlsx"]
cidades <- arquivos_csv  |>
  map_chr(~ str_split(.x, "\\.")[[1]][1])

inscritos <- read_csv("presenca.csv")
nomes <- inscritos$nome |> map_chr(~ str_to_title(.x)) |>
  sort()
nomes <- c(nomes, rep("", 28))
id <- paste0("id_", 1:50)

set.seed(20241210)
df <- tibble( 
  `.csv` = cidades |>
      map_chr(\(nome) glue("[{nome}.csv](cidades_enem_2023/csv/{nome}.csv)")),
  `.xlsx` = cidades |>
      map_chr(\(nome) glue("[{nome}.xlsx](cidades_enem_2023/xlsx/{nome}.xlsx)"))
) |>
  slice_sample(n = 50) |>
  mutate(id, nome = nomes) |>
  relocate(id, nome, .before = `.csv`)

knitr::kable(df)
```

## `R` e `Rstudio`

Neste curso, a IDE vamos utilizar é o [`RStudio`](https://posit.co/downloads/){target="_blank"}. Outras opções populares em ciência de dados são o [`VScode`](https://code.visualstudio.com/Download){target="_blank"} da Microsoft e [`JupyterLab`](https://jupyter.org/install){target="_blank"}, caso você tenha familiaridade ou já trabalhe com este editores sinta a vontade para usá-los.

Caso você não queria ou não possa realizar instalações em seu computador, recomendamos que você use as plataformas [Google Colaboratory](https://colab.research.google.com/){target="_blank"} e/ou [Posit Cloud](https://posit.cloud){target="_blank"}. Recomendamos o uso da plataforma [Posit Cloud](https://posit.cloud){target="_blank"} pelo mesmo estilo e aspecto visual do aplicativo [`RStudio`](https://posit.co/downloads/){target="_blank"}.

### Instalação -`R`

Para instalar o `R` em seu computador, basta seguir as instruções em [cran.r-project.org](https://cran.r-project.org/). É necessário que você instale a versão 4.1 ou superior do R.

### Instalação - `RStudio`

Depois de ter instalado o R, siga as instruções de instalação em [posit.co/downloads](https://posit.co/downloads/).

---
